org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true

mod_id=ionclient
mod_name=ION Client
mod_version=1.2.0-beta.1
mod_group=de.ionnetwork
mod_description=Official ION Network client mod. Pins the ION Network server to your multiplayer list.
mod_author=ION Network
mod_homepage=https://ion-network.de

# ---- 1.8.9 ----
mc189_forge_version=11.15.1.2318-1.8.9
mc189_legacy_fabric_loader=0.16.14
mc189_mcp_channel=stable
mc189_mcp_version=22-1.8.9

# ---- 1.21.1 ----
mc1211_fabric_loader=0.16.14
mc1211_neoforge_version=252
mc1211_forge_version=52.1.16
